[package]
name = "dsl"
version = "0.1.0"
edition = "2021"

[dependencies]
ahnlich_types = { path = "../types", version = "*" }
pest = "2.7.13"
pest_derive = "2.7.13"
thiserror.workspace = true
hex = "0.4.3"
[dev-dependencies]
pretty_assertions.workspace = true

